# Generated by Django 4.0 on 2023-05-23 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_title', models.CharField(max_length=512, unique=True, verbose_name='Title')),
                ('project_img', models.ImageField(upload_to='projects/', verbose_name='Image')),
                ('project_body', models.TextField(verbose_name='Description')),
                ('project_date', models.DateTimeField(auto_now_add=True, verbose_name='Date and Time')),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
            },
        ),
    ]
