# Generated by Django 4.0 on 2023-05-25 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_price',
            field=models.FloatField(default=0, verbose_name='Time'),
        ),
        migrations.AddField(
            model_name='project',
            name='project_time',
            field=models.IntegerField(default=0, verbose_name='Time'),
        ),
    ]
